import type { TranslationMap } from '../types.js';

/** Hindi translations — falls back to English for missing keys at runtime. */
export const stringsHi: TranslationMap = {
  'auth.login.title': 'शुरू करने के लिए लॉगिन करें',
  'auth.login.mobilePlaceholder': 'मोबाइल नंबर दर्ज करें',
  'auth.login.continue': 'जारी रखें',
  'auth.login.or': 'या',
  'auth.login.google': 'Google के साथ जारी रखें',
  'auth.login.language': 'भाषा: {language}',
  'auth.login.terms': 'नियम और शर्तें',
  'auth.login.privacy': 'गोपनीयता नीति',
  'auth.header.partner': 'पार्टनर',
  'auth.header.tagline': 'ड्राइव • कमाएँ • जुड़ें',
  'auth.otp.title': 'OTP सत्यापन',
  'auth.otp.edit': 'संपादित करें',
  'auth.otp.verify': 'सत्यापित करें',
  'auth.otp.didntReceive': 'कोड नहीं मिला?',
  'auth.otp.resend': 'फिर से भेजें',
  'tabs.home': 'होम',
  'tabs.earnings': 'कमाई',
  'tabs.security': 'सुरक्षा',
  'tabs.activity': 'गतिविधि',
  'tabs.account': 'खाता',
  'security.placeholder': 'आपातकालीन SOS और सुरक्षा टूल यहाँ दिखेंगे। हर यात्रा में सुरक्षित रहें।',
  'home.online': 'आप ऑनलाइन हैं',
  'home.offline': 'आप ऑफ़लाइन हैं',
  'common.continue': 'जारी रखें',
  'common.cancel': 'रद्द करें',
  'common.save': 'सेव करें',
};
