import type { TranslationMap } from '../types.js';

/** Urdu translations — isRtl: true at locale level. */
export const stringsUr: TranslationMap = {
  'auth.login.title': 'شروع کرنے کے لیے لاگ ان کریں',
  'auth.login.mobilePlaceholder': 'موبائل نمبر درج کریں',
  'auth.login.continue': 'جاری رکھیں',
  'auth.login.or': 'یا',
  'auth.login.google': 'Google کے ساتھ جاری رکھیں',
  'auth.login.language': 'زبان: {language}',
  'auth.login.terms': 'شرائط و ضوابط',
  'auth.login.privacy': 'پرائیویسی پالیسی',
  'auth.header.partner': 'پارٹنر',
  'auth.header.tagline': 'ڈرائیو • کمائیں • جڑیں',
  'auth.otp.title': 'OTP تصدیق',
  'auth.otp.edit': 'ترمیم',
  'auth.otp.verify': 'تصدیق کریں',
  'auth.otp.didntReceive': 'کوڈ نہیں ملا؟',
  'auth.otp.resend': 'دوبارہ بھیجیں',
  'tabs.home': 'ہوم',
  'tabs.earnings': 'کمائی',
  'tabs.security': 'سیکورٹی',
  'tabs.activity': 'سرگرمی',
  'tabs.account': 'اکاؤنٹ',
  'security.placeholder': 'ایمرجنسی SOS اور سیفٹی ٹولز یہاں آئیں گے۔ ہر سفر میں محفوظ رہیں۔',
  'home.online': 'آپ آن لائن ہیں',
  'home.offline': 'آپ آف لائن ہیں',
  'common.continue': 'جاری رکھیں',
  'common.cancel': 'منسوخ',
  'common.save': 'محفوظ کریں',
};
