import { BaseRepository, DatabaseService } from '@core/database';
import type { TransactionClient } from '@core/database/TransactionManager';
import type { UserSession } from '@core/database/types';

/** Fields needed to open a session. The session id (`sid`) is generated by the
 *  database default (uuid v7); expiry is decided by the caller (auth doc 02). */
export interface CreateSessionInput {
  userId: string;
  deviceId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  loginMethod?: string | null;
  expiresAt: Date;
}

/**
 * Data access for `UserSession`.
 *
 * A session is one authenticated context on one device, identified by its `sid`.
 * "Active" means `revokedAt IS NULL AND expiresAt > now`; the concurrency-cap
 * queries below back the service-owned eviction policy (auth doc 02 §5.1).
 * Prisma-only, no business rules — the cap value and eviction choice live in the
 * service.
 */
export class SessionRepository extends BaseRepository {
  /** @param databaseService Resolved singleton facade over the Prisma client. */
  constructor(databaseService: DatabaseService) {
    super(databaseService);
  }

  /**
   * Open a new session.
   * @param input Owner user, optional device/ip, and the expiry instant.
   * @returns The created session (its `id` is the `sid`).
   */
  async create(input: CreateSessionInput, tx?: TransactionClient): Promise<UserSession> {
    return (tx ?? this.client).userSession.create({
      data: {
        userId: input.userId,
        expiresAt: input.expiresAt,
        ...(input.deviceId != null ? { deviceId: input.deviceId } : {}),
        ...(input.ipAddress != null ? { ipAddress: input.ipAddress } : {}),
        ...(input.userAgent != null ? { userAgent: input.userAgent } : {}),
        ...(input.loginMethod != null ? { loginMethod: input.loginMethod } : {}),
      },
    });
  }

  /**
   * Fetch a session by its `sid`.
   * @param id Session UUID (`sid`).
   * @param tx Transaction client to join, so a revocation can read the owner it
   *           is about to audit inside the same unit of work (omit for a
   *           standalone read).
   * @returns The session, or `null` if unknown.
   */
  async findById(id: string, tx?: TransactionClient): Promise<UserSession | null> {
    return (tx ?? this.client).userSession.findUnique({ where: { id } });
  }

  /**
   * List a user's currently active sessions, oldest first.
   * @param userId Owner user UUID.
   * @param now Reference instant for the expiry check.
   * @param tx Transaction client to join, so a caller that revokes in bulk
   *           enumerates exactly the rows its own update will touch.
   * @returns Active sessions ordered by `createdAt` ascending.
   */
  async findActiveByUser(
    userId: string,
    now: Date = new Date(),
    tx?: TransactionClient,
  ): Promise<UserSession[]> {
    return (tx ?? this.client).userSession.findMany({
      where: { userId, revokedAt: null, expiresAt: { gt: now } },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Count a user's currently active sessions (drives the cap check).
   * @param userId Owner user UUID.
   * @param now Reference instant for the expiry check.
   * @returns Number of active sessions.
   */
  async countActiveByUser(userId: string, now: Date = new Date()): Promise<number> {
    return this.client.userSession.count({
      where: { userId, revokedAt: null, expiresAt: { gt: now } },
    });
  }

  /**
   * Fetch the oldest active session for a user (the cap-eviction candidate).
   * @param userId Owner user UUID.
   * @param now Reference instant for the expiry check.
   * @returns The oldest active session, or `null` if none are active.
   */
  async findOldestActiveByUser(
    userId: string,
    now: Date = new Date(),
  ): Promise<UserSession | null> {
    return this.client.userSession.findFirst({
      where: { userId, revokedAt: null, expiresAt: { gt: now } },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * List a device's currently active sessions (for device revocation).
   * @param deviceId The bound device's UUID (`UserDevice.id`).
   * @param now Reference instant for the expiry check.
   * @returns Active sessions bound to the device.
   */
  async findActiveByDevice(deviceId: string, now: Date = new Date()): Promise<UserSession[]> {
    return this.client.userSession.findMany({
      where: { deviceId, revokedAt: null, expiresAt: { gt: now } },
    });
  }

  /**
   * Atomically revoke a session only if it is still active. Uses a conditional
   * `updateMany ... WHERE revoked_at IS NULL` so concurrent logout/eviction
   * requests cannot both "win" and duplicate side effects.
   * @param id Session UUID (`sid`).
   * @param reason Revocation reason (logout | suspension | cap_evicted | device_revoked | reuse_detected).
   * @param revokedAt Revocation timestamp (defaults to now).
   * @param tx Transaction client to join, so the revoke and its audit event commit
   *           atomically (omit for a standalone write).
   * @returns `true` if this call performed the revocation; `false` if it was
   *          already revoked or does not exist.
   */
  async revoke(
    id: string,
    reason: string,
    revokedAt: Date = new Date(),
    tx?: TransactionClient,
  ): Promise<boolean> {
    const { count } = await (tx ?? this.client).userSession.updateMany({
      where: { id, revokedAt: null },
      data: { revokedAt, revokedReason: reason },
    });
    return count === 1;
  }

  /**
   * Revoke every active session for a user (logout-all / suspension).
   * @param userId Owner user UUID.
   * @param reason Revocation reason.
   * @param revokedAt Revocation timestamp (defaults to now).
   * @param tx Transaction client to join, so the bulk revoke and its per-session
   *           audit events commit atomically (omit for a standalone write).
   * @returns Count of sessions revoked.
   */
  async revokeAllByUser(
    userId: string,
    reason: string,
    revokedAt: Date = new Date(),
    tx?: TransactionClient,
  ): Promise<number> {
    const { count } = await (tx ?? this.client).userSession.updateMany({
      where: { userId, revokedAt: null },
      data: { revokedAt, revokedReason: reason },
    });
    return count;
  }

  /**
   * Update a session's last-seen timestamp.
   * @param id Session UUID (`sid`).
   * @param at Observation instant.
   */
  async touchLastSeen(id: string, at: Date = new Date()): Promise<void> {
    await this.client.userSession.update({ where: { id }, data: { lastSeenAt: at } });
  }
}
