import { aliasTo, createContainer, InjectionMode } from 'awilix';
import { registerDatabaseModule } from './database/DatabaseModule';
import { registerRedisModule } from './cache/RedisModule';
import { registerEventsModule } from './events';
import { registerNotificationModule } from '@modules/notifications';
import { registerAuthRepositories } from '@modules/auth/repositories';
import { registerTokenServices } from '@modules/auth/services';
import { registerOtpServices } from '@modules/auth/services/otp';
import { registerSessionServices } from '@modules/auth/services/session';
import { registerAuthService } from '@modules/auth';
import { registerUserRepositories, registerUserService } from '@modules/users';
import { registerFileModule, registerFileRepositories } from '@modules/files';
import { registerPaymentsModule } from '@modules/payments';
import { registerPricingModule } from '@modules/pricing';
import { registerAdminModule } from '@modules/admin';
import { registerMatchingModule } from '@modules/matching';
import { registerRatingModule } from '@modules/rating';
import { registerRidesModule } from '@modules/rides';
import { registerDriversModule } from '@modules/drivers';
import { registerVehiclesModule } from '@modules/vehicles';
import { registerGeoModule } from '@modules/geo';
import { registerRealtimeModule } from '@modules/realtime';
export const container = createContainer({ injectionMode: InjectionMode.CLASSIC });
registerDatabaseModule(container);
registerRedisModule(container);
registerEventsModule(container);
registerNotificationModule(container);
registerAuthRepositories(container);
registerUserRepositories(container);
registerFileRepositories(container);
registerTokenServices(container);
registerOtpServices(container);
registerSessionServices(container);
registerAuthService(container);
registerUserService(container);
registerFileModule(container);
registerPaymentsModule(container);
registerGeoModule(container);
registerRealtimeModule(container);
registerDriversModule(container);
registerVehiclesModule(container);
registerPricingModule(container);
registerAdminModule(container);
registerMatchingModule(container);
registerRatingModule(container);
registerRidesModule(container);
container.register({
  db: aliasTo('databaseService'),
  redis: aliasTo('redisService'),
});
