export const RIDE_STATUS = {
  REQUESTED: 'REQUESTED',
  SEARCHING: 'SEARCHING',
  ACCEPTED: 'ACCEPTED',
  DRIVER_ARRIVING: 'DRIVER_ARRIVING',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_DRIVER: 'CANCELLED_BY_DRIVER',
  CANCELLED_BY_SYSTEM: 'CANCELLED_BY_SYSTEM',
  NO_DRIVERS_FOUND: 'NO_DRIVERS_FOUND',
} as const;

export type RideStatusType = (typeof RIDE_STATUS)[keyof typeof RIDE_STATUS];

export const RIDE_REQUEST_STATUS = {
  CREATED: 'CREATED',
  SEARCHING: 'SEARCHING',
  MATCHED: 'MATCHED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED',
} as const;

export type RideRequestStatusType = (typeof RIDE_REQUEST_STATUS)[keyof typeof RIDE_REQUEST_STATUS];

export const RIDE_OTP_TTL_MINUTES = 15;

export const RIDE_OTP_MAX_ATTEMPTS = 5;

export const RIDE_OTP_LENGTH = 6;

export const DISPATCH_RESPONSE = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  TIMEOUT: 'TIMEOUT',
  CANCELLED: 'CANCELLED',
} as const;

export type DispatchResponseType = (typeof DISPATCH_RESPONSE)[keyof typeof DISPATCH_RESPONSE];
