#!/usr/bin/env sh
. "$(dirname "$0")/common.sh"

printf "\033[36m🚀 Running pre-push checks...\033[0m\n"

npm run typecheck

# Unit Tests (later)
# npm run test

# Build (later)
# npm run build

printf "\033[32m✅ Pre-push checks passed.\033[0m\n"
